"""Import all plugin modules so their registrations run.
Details: docs/dev/core/bootstrap.md#module
"""
from __future__ import annotations

from agents import local_agent  # noqa: F401  (registers "local")
from agents import mock_agent  # noqa: F401  (registers "mock")
from generators import accessibility_act  # noqa: F401  (registers "accessibility")
from generators import architecture_calm  # noqa: F401  (registers "architecture")
from generators import aria_tree  # noqa: F401  (registers "tree")
from generators import asyncapi  # noqa: F401  (registers "asyncapi" - never in core/config.py's default list, docs/adr/0018)
from generators import browser_support_matrix  # noqa: F401  (registers "browser-support-matrix" - never in core/config.py's default list, docs/adr/0028)
from generators import change_log  # noqa: F401  (registers "change-log")
from generators import content_inventory  # noqa: F401  (registers "content-inventory")
from generators import coverage  # noqa: F401  (registers "coverage")
from generators import custom_elements  # noqa: F401  (registers "catalog")
from generators import data_model  # noqa: F401  (registers "data-model")
from generators import decisions_adr  # noqa: F401  (registers "decisions.adr")
from generators import design_tokens  # noqa: F401  (registers "tokens")
from generators import evidence_log  # noqa: F401  (registers "evidence-log")
from generators import gherkin  # noqa: F401  (registers "gherkin")
from generators import glossary  # noqa: F401  (registers "glossary")
from generators import graph_export  # noqa: F401  (registers "export")
from generators import i18n_inventory  # noqa: F401  (registers "i18n-inventory" - never in core/config.py's default list, docs/adr/0027)
from generators import openapi  # noqa: F401  (registers "openapi")
from generators import performance_baseline  # noqa: F401  (registers "performance-baseline")
from generators import redaction_log  # noqa: F401  (registers "redaction-log")
from generators import requirements  # noqa: F401  (registers "prd")
from generators import risk_register  # noqa: F401  (registers "risk-register")
from generators import test_plan  # noqa: F401  (registers "test-plan")
from generators import usability_act  # noqa: F401  (registers "usability")
from generators import user_flows  # noqa: F401  (registers "flows")
from database.ladybug import store as ladybug_store  # noqa: F401  (registers "ladybug", "memory")
