"""Core interfaces and data contracts for the Pragma micro-kernel.

`GraphStore` is composed from several topic-split ABCs (`_ComponentStore
Interface`, `_ComponentFamilyInterface`, `_RequestFamilyInterface`,
`_TextContentInterface`, `_ContainmentInterface`, `_PageExtrasInterface`,
each its own file) via multiple inheritance - split out once this file
crossed the file-size SPLIT threshold (626 lines), growing by roughly one
new capability per storage-migration phase. Mirrors the split every
concrete backend already uses (`DuckDBGraphStore`'s own component/family/
text-content/page-extras mixins, and the retired Neo4j backend's before
it) - the interface itself had never had the same treatment before now.
This file keeps only
`Agent` and the core Page/Site/navigation-edge methods that don't belong
to any of those split-out concerns.

Details: docs/dev/core/interfaces.md#module
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Tuple

from ._analysis_interface import _AnalysisInterface
from ._component_family_interface import _ComponentFamilyInterface
from ._component_store_interface import _ComponentStoreInterface
from ._containment_interface import _ContainmentInterface
from ._page_extras_interface import _PageExtrasInterface
from ._request_family_interface import _RequestFamilyInterface
from ._text_content_interface import _TextContentInterface
from .data_contracts import (  # noqa: F401 - re-exported, see module docstring below
    ComponentFacts,
    ComponentFamily,
    InferredRequest,
    PageState,
    VisitStep,
)

# PageState/ComponentFacts/ComponentFamily/InferredRequest are re-exported
# (imported above, not redefined) for backward compatibility with every
# existing `from core.interfaces import ComponentFacts` (etc.) import
# site - the plain-data-contract split moved their real definitions to
# `data_contracts.py`. See that file's own module docstring for why.


class Agent(ABC):
    """Interface for AI agent backends."""

    @abstractmethod
    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Return text generated by an LLM or agent backend."""
        raise NotImplementedError


class GraphStore(
    _ComponentStoreInterface, _ComponentFamilyInterface, _RequestFamilyInterface,
    _TextContentInterface, _ContainmentInterface, _PageExtrasInterface, _AnalysisInterface, ABC,
):
    """Interface for the crawl graph's persistence/query backend, scoped per site.
    Details: docs/dev/core/interfaces.md#graphstore
    """

    @abstractmethod
    def connect(self) -> None:
        """Establish the connection and idempotently ensure schema exists."""
        raise NotImplementedError

    @abstractmethod
    def close(self) -> None:
        """Release the connection. Safe to call even if never connected."""
        raise NotImplementedError

    @abstractmethod
    def upsert_page(
        self,
        site: str,
        url: str,
        status: str = "Pending",
        components: int = 0,
        context: str = "",
        label: str = "",
        description: str = "",
        title: str = "",
    ) -> None:
        """Create or update a page node for `site`; never clobbers Finished with Pending.
        Details: docs/dev/core/interfaces.md#upsert_page
        """
        raise NotImplementedError

    @abstractmethod
    def get_page_descriptions(self, site: str) -> Dict[str, str]:
        """{url: description} for every page of `site` that has one recorded."""
        raise NotImplementedError

    @abstractmethod
    def get_page_titles(self, site: str) -> Dict[str, str]:
        """{url: title} for every page of `site` that has one recorded.
        Details: docs/dev/core/interfaces.md#get_page_titles
        """
        raise NotImplementedError

    @abstractmethod
    def is_visited(self, site: str, url: str) -> bool:
        """Whether this page is a Finished node in the graph for `site`."""
        raise NotImplementedError

    @abstractmethod
    def get_pending(self, site: str, limit: Optional[int] = None) -> List[str]:
        """Up to `limit` Pending page urls for `site`, sorted ascending. Unbounded if limit is None."""
        raise NotImplementedError

    @abstractmethod
    def get_page_label(self, site: str, url: str) -> Optional[str]:
        """The link-text label recorded for a page, if any."""
        raise NotImplementedError

    @abstractmethod
    def record_link(self, site: str, from_url: str, to_url: str, label: str) -> None:
        """Record a discovered link and its visible text, distinct from a taken navigation.
        Details: docs/dev/core/interfaces.md#record_link
        """
        raise NotImplementedError

    def record_links(self, site: str, from_url: str, links: List[Dict[str, str]]) -> None:
        """Batched `record_link`: each item is `{"to_url", "label"}`. Not
        abstract - the default loops the per-item call, so only a backend
        that can do better (e.g. one round-trip covering the whole page's
        links) needs to override it.
        Details: docs/dev/core/interfaces.md#record_links
        """
        for item in links:
            self.record_link(site, from_url, item["to_url"], item.get("label", ""))

    @abstractmethod
    def get_link_label(self, site: str, from_url: str, to_url: str) -> Optional[str]:
        """The label of a specific from->to link discovery, if one was ever recorded."""
        raise NotImplementedError

    @abstractmethod
    def record_edge(
        self, site: str, from_url: str, to_url: str, component: str, action: str, run_id: str = "",
    ) -> None:
        """Record a successful navigation from `from_url` to `to_url` for `site`.

        Idempotent per `(site, from_url, to_url, component, action)`: a
        transition observed again (the same page re-crawled, or the same
        control clicked twice) bumps that edge's `observation_count` rather
        than adding a second edge - a duplicated edge previously inflated
        every dependency/coupling count read off `get_edges` by however many
        times a site had been re-crawled, with no way to tell "seen once"
        from "seen ten times" apart from counting raw rows.

        Args:
            run_id: which crawl run this observation belongs to, if the
                caller tracks one. `""` (the default) records the
                observation without provenance - every existing call site
                keeps working unchanged. Backends that support it stamp
                `first_seen_run` once (on the edge's first observation) and
                `last_seen_run` on every observation after, so "did this
                transition disappear/appear between two runs" is answerable
                without a full graph diff.
        """
        raise NotImplementedError

    @abstractmethod
    def get_edges(self, site: str) -> List[Dict[str, Any]]:
        """All recorded edges for `site`, each
        `{"from", "component", "action", "to", "observation_count",
        "first_seen_run", "last_seen_run"}`, in insertion order (first-seen
        order, for an edge observed more than once).
        `observation_count` is `1` and both run fields are `""` for an edge
        recorded through a call site that never passed `run_id`.
        """
        raise NotImplementedError

    @abstractmethod
    def get_progress_table_rows(self, site: str) -> List[Dict[str, Any]]:
        """All page rows for `site` as {"url", "status", "components", "label"}, sorted."""
        raise NotImplementedError

    @abstractmethod
    def count_visited(self, site: str) -> Tuple[int, int]:
        """(finished_count, total_count) of pages tracked for `site`."""
        raise NotImplementedError

    @abstractmethod
    def get_loop_signals(self, site: str, url: str) -> List[Dict[str, str]]:
        """Distinct {"component", "from"} pairs of edges already leading into `url`."""
        raise NotImplementedError

    @abstractmethod
    def clear_site(self, site: str) -> None:
        """Delete every page/edge/link/component tracked for `site`.
        Details: docs/dev/core/interfaces.md#clear_site
        """
        raise NotImplementedError
