"""Core interfaces and data contracts for the Pragma micro-kernel.

`GraphStore` - the 41-method ABC this file used to compose from seven
topic-split mixins (`_ComponentStoreInterface`, `_ComponentFamilyInterface`,
`_RequestFamilyInterface`, `_TextContentInterface`, `_ContainmentInterface`,
`_PageExtrasInterface`, `_AnalysisInterface`) - is gone, along with all
seven of those files. Storage-migration plan step 6: with a single graph-
store implementation (`database/ladybug/store.py::LadybugGraphStore`)
rather than several interchangeable backends, a formal interface bought
ceremony without the substitutability it exists for. Every call site that
used to type a parameter as `GraphStore` now types it `Any` - Python's
duck typing needs no declared interface to call a method that exists.

This file keeps `Agent` (still genuinely pluggable - `agents/local_agent.py`,
`agents/mock_agent.py`) and the re-exported data contracts below.

Details: docs/dev/core/interfaces.md#module
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Dict, List, Optional

from .data_contracts import (  # noqa: F401 - re-exported, see module docstring below
    ComponentFacts,
    ComponentFamily,
    CompositeFamily,
    InferredRequest,
    PageState,
    SemanticEntity,
    SemanticField,
    VisitStep,
)

# Every name above is re-exported
# (imported above, not redefined) for backward compatibility with every
# existing `from core.interfaces import ComponentFacts` (etc.) import
# site - the plain-data-contract split moved their real definitions to
# `data_contracts.py`. See that file's own module docstring for why.


class Agent(ABC):
    """Interface for AI agent backends."""

    @abstractmethod
    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Return text generated by an LLM or agent backend."""
        raise NotImplementedError

    def converse(self, messages: List[Dict[str, str]], system_instruction: Optional[str] = None) -> str:
        """Multi-turn chat (ADR-0033, ticket #149) - `messages` is
        `[{"role": "user"|"assistant", "content": str}, ...]`, oldest
        first. Concrete with a trivial default, not abstract: no history
        at all, just the last user turn passed straight to `generate()` -
        every existing subclass keeps working with zero changes, since
        this project's every document-generation call site only ever
        used single-shot `generate()` and has no reason to know
        `converse()` exists. An agent whose backend actually supports a
        real message history (`LocalAgent`) overrides this to use it.
        Details: docs/dev/core/interfaces.md#agentconverse
        """
        last_user = next((m["content"] for m in reversed(messages) if m["role"] == "user"), None)
        if last_user is None:
            raise ValueError("converse() needs at least one message with role='user'")
        return self.generate(last_user, system_instruction)
