"""Core interfaces and data contracts for the Pragma micro-kernel.

`GraphStore` - the 41-method ABC this file used to compose from seven
topic-split mixins (`_ComponentStoreInterface`, `_ComponentFamilyInterface`,
`_RequestFamilyInterface`, `_TextContentInterface`, `_ContainmentInterface`,
`_PageExtrasInterface`, `_AnalysisInterface`) - is gone, along with all
seven of those files. Storage-migration plan step 6: with a single graph-
store implementation (`database/ladybug/store.py::LadybugGraphStore`)
rather than several interchangeable backends, a formal interface bought
ceremony without the substitutability it exists for. Every call site that
used to type a parameter as `GraphStore` now types it `Any` - Python's
duck typing needs no declared interface to call a method that exists.

This file keeps `Agent` (still genuinely pluggable - `agents/local_agent.py`,
`agents/mock_agent.py`) and the re-exported data contracts below.

Details: docs/dev/core/interfaces.md#module
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional

from .data_contracts import (  # noqa: F401 - re-exported, see module docstring below
    ComponentFacts,
    ComponentFamily,
    InferredRequest,
    PageState,
    VisitStep,
)

# PageState/ComponentFacts/ComponentFamily/InferredRequest are re-exported
# (imported above, not redefined) for backward compatibility with every
# existing `from core.interfaces import ComponentFacts` (etc.) import
# site - the plain-data-contract split moved their real definitions to
# `data_contracts.py`. See that file's own module docstring for why.


class Agent(ABC):
    """Interface for AI agent backends."""

    @abstractmethod
    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Return text generated by an LLM or agent backend."""
        raise NotImplementedError
