"""Core interfaces and data contracts for the Pragma micro-kernel.
Details: docs/dev/core/interfaces.md#module
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


@dataclass
class PageState:
    """Normalized snapshot of a crawled page (the Crawler -> orchestrator contract)."""

    url: str
    title: str = ""
    metadata: Dict[str, str] = field(default_factory=dict)
    components: List[Dict[str, Any]] = field(default_factory=list)
    links: List[Dict[str, str]] = field(default_factory=list)
    # Short (~300 char) page summary; "" if the backend doesn't extract it.
    # Details: docs/dev/core/interfaces.md#pagestatedescription
    description: str = ""
    # Meaningful (xhr/fetch) requests triggered by the interaction, if any.
    # Details: docs/dev/core/interfaces.md#pagestatenetwork_requests
    network_requests: List[Dict[str, Any]] = field(default_factory=list)
    # Non-interactive prose, captured once per page visit alongside components.
    # Details: docs/dev/core/interfaces.md#pagestatetext_content
    text_content: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class ComponentFacts:
    """DOM-attribute and computed-style facts about a discovered element,
    beyond the core identity/geometry `record_component` already took as
    named params. Grouped into one object rather than growing that method's
    own argument list further - see docs/dev/core/interfaces.md#componentfacts
    for which facts are here and, notably, which one (`value`) isn't and why.
    """

    css_class: str = ""
    element_id: str = ""
    href: str = ""
    placeholder: str = ""
    label: str = ""
    name: str = ""
    disabled: bool = False
    required: bool = False
    form: str = ""
    color: str = ""
    background_color: str = ""
    font_size: str = ""
    font_weight: str = ""
    display: str = ""
    position: str = ""


class Agent(ABC):
    """Interface for AI agent backends."""

    @abstractmethod
    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Return text generated by an LLM or agent backend."""
        raise NotImplementedError


class GraphStore(ABC):
    """Interface for the crawl graph's persistence/query backend, scoped per site.
    Details: docs/dev/core/interfaces.md#graphstore
    """

    @abstractmethod
    def connect(self) -> None:
        """Establish the connection and idempotently ensure schema exists."""
        raise NotImplementedError

    @abstractmethod
    def close(self) -> None:
        """Release the connection. Safe to call even if never connected."""
        raise NotImplementedError

    @abstractmethod
    def upsert_page(
        self,
        site: str,
        url: str,
        status: str = "Pending",
        components: int = 0,
        context: str = "",
        label: str = "",
        description: str = "",
        title: str = "",
    ) -> None:
        """Create or update a page node for `site`; never clobbers Finished with Pending.
        Details: docs/dev/core/interfaces.md#upsert_page
        """
        raise NotImplementedError

    @abstractmethod
    def get_page_descriptions(self, site: str) -> Dict[str, str]:
        """{url: description} for every page of `site` that has one recorded."""
        raise NotImplementedError

    @abstractmethod
    def get_page_titles(self, site: str) -> Dict[str, str]:
        """{url: title} for every page of `site` that has one recorded.
        Details: docs/dev/core/interfaces.md#get_page_titles
        """
        raise NotImplementedError

    @abstractmethod
    def is_visited(self, site: str, url: str) -> bool:
        """Whether this page is a Finished node in the graph for `site`."""
        raise NotImplementedError

    @abstractmethod
    def get_pending(self, site: str, limit: Optional[int] = None) -> List[str]:
        """Up to `limit` Pending page urls for `site`, sorted ascending. Unbounded if limit is None."""
        raise NotImplementedError

    @abstractmethod
    def get_page_label(self, site: str, url: str) -> Optional[str]:
        """The link-text label recorded for a page, if any."""
        raise NotImplementedError

    @abstractmethod
    def record_link(self, site: str, from_url: str, to_url: str, label: str) -> None:
        """Record a discovered link and its visible text, distinct from a taken navigation.
        Details: docs/dev/core/interfaces.md#record_link
        """
        raise NotImplementedError

    def record_links(self, site: str, from_url: str, links: List[Dict[str, str]]) -> None:
        """Batched `record_link`: each item is `{"to_url", "label"}`. Not
        abstract - the default loops the per-item call, so only a backend
        that can do better (e.g. one round-trip covering the whole page's
        links) needs to override it.
        Details: docs/dev/core/interfaces.md#record_links
        """
        for item in links:
            self.record_link(site, from_url, item["to_url"], item.get("label", ""))

    @abstractmethod
    def get_link_label(self, site: str, from_url: str, to_url: str) -> Optional[str]:
        """The label of a specific from->to link discovery, if one was ever recorded."""
        raise NotImplementedError

    @abstractmethod
    def record_edge(self, site: str, from_url: str, to_url: str, component: str, action: str) -> None:
        """Record a successful navigation from `from_url` to `to_url` for `site`."""
        raise NotImplementedError

    @abstractmethod
    def get_edges(self, site: str) -> List[Dict[str, str]]:
        """All recorded edges for `site`, each {"from", "component", "action", "to"}, in insertion order."""
        raise NotImplementedError

    @abstractmethod
    def get_progress_table_rows(self, site: str) -> List[Dict[str, Any]]:
        """All page rows for `site` as {"url", "status", "components", "label"}, sorted."""
        raise NotImplementedError

    @abstractmethod
    def count_visited(self, site: str) -> Tuple[int, int]:
        """(finished_count, total_count) of pages tracked for `site`."""
        raise NotImplementedError

    @abstractmethod
    def get_loop_signals(self, site: str, url: str) -> List[Dict[str, str]]:
        """Distinct {"component", "from"} pairs of edges already leading into `url`."""
        raise NotImplementedError

    @abstractmethod
    def clear_site(self, site: str) -> None:
        """Delete every page/edge/link/component tracked for `site`.
        Details: docs/dev/core/interfaces.md#clear_site
        """
        raise NotImplementedError

    # Component-level frontier: per-element interacted state, keyed by
    # (site, page_url, path). Details: docs/dev/core/interfaces.md#component-level-frontier

    @abstractmethod
    def record_component(
        self,
        site: str,
        page_url: str,
        path: str,
        tag: str = "",
        text: str = "",
        role: str = "",
        input_type: str = "",
        visible: bool = True,
        layer: str = "semantic",
        x: Optional[float] = None,
        y: Optional[float] = None,
        width: Optional[float] = None,
        height: Optional[float] = None,
        component_type: str = "",
        facts: Optional[ComponentFacts] = None,
    ) -> None:
        """Create or refresh a Component node's descriptive fields only.
        `facts` defaults to an empty `ComponentFacts()` when omitted, same as
        every other optional field here defaulting to its own "unknown" value.
        Details: docs/dev/core/interfaces.md#record_component
        """
        raise NotImplementedError

    def record_components(self, site: str, page_url: str, components: List[Dict[str, Any]]) -> None:
        """Batched `record_component`: each item is a kwargs dict matching
        `record_component`'s own signature (minus `site`/`page_url`). Not
        abstract - the default loops the per-item call; a backend can
        override it to write a whole discovery pass's worth of components
        in one round-trip instead of one per component.
        Details: docs/dev/core/interfaces.md#record_components
        """
        for item in components:
            self.record_component(site, page_url, **item)

    @abstractmethod
    def record_component_options(self, site: str, page_url: str, path: str, options: str) -> None:
        """Overwrite a Component's JSON-encoded `options` field; auto-creates the node.
        Details: docs/dev/core/interfaces.md#record_component_options
        """
        raise NotImplementedError

    @abstractmethod
    def record_component_interaction(
        self,
        site: str,
        page_url: str,
        path: str,
        action: str,
        value: str = "",
        resulting_url: str = "",
        source_path: str = "",
    ) -> None:
        """Mark a component as interacted with and append one interaction record.
        `source_path` names the specific member that acted when `path` is a
        consolidated choice-group/dropdown's representative node rather than
        the member itself - "" when they're the same (the ordinary case).
        Details: docs/dev/core/interfaces.md#record_component_interaction
        """
        raise NotImplementedError

    @abstractmethod
    def record_component_network(self, site: str, page_url: str, path: str, requests_json: str) -> None:
        """Append one JSON-encoded batch of meaningful network requests to a Component.
        Details: docs/dev/core/interfaces.md#record_component_network
        """
        raise NotImplementedError

    @abstractmethod
    def get_component_states(self, site: str, page_url: str) -> Dict[str, Dict[str, Any]]:
        """All known components for one page, one query per page visit.
        Details: docs/dev/core/interfaces.md#get_component_states
        """
        raise NotImplementedError

    @abstractmethod
    def count_unexplored_components(self, site: str, semantic_only: bool = True) -> Tuple[int, int]:
        """(unexplored_count, total_count) of components tracked across all of `site`.
        Details: docs/dev/core/interfaces.md#count_unexplored_components
        """
        raise NotImplementedError

    @abstractmethod
    def get_pages_with_unexplored_components(
        self, site: str, limit: Optional[int] = None, semantic_only: bool = True
    ) -> List[Dict[str, Any]]:
        """[{"url", "unexplored_count"}] for pages with >=1 unexplored component, sorted descending."""
        raise NotImplementedError

    @abstractmethod
    def page_has_unexplored_components(self, site: str, url: str, semantic_only: bool = True) -> bool:
        """Whether `url` has at least one un-interacted-with component tracked."""
        raise NotImplementedError

    @abstractmethod
    def get_component_ledger(self, site: str) -> Dict[str, Dict[str, Dict[str, Any]]]:
        """Full per-component interaction/options/network-request record for all of `site`.
        Details: docs/dev/core/interfaces.md#get_component_ledger
        """
        raise NotImplementedError

    # Static text content: a separate node kind from Component, deliberately.
    # Details: docs/dev/core/interfaces.md#static-text-content

    @abstractmethod
    def record_text_content(
        self,
        site: str,
        page_url: str,
        path: str,
        tag: str = "",
        text: str = "",
        visible: bool = True,
        x: Optional[float] = None,
        y: Optional[float] = None,
        width: Optional[float] = None,
        height: Optional[float] = None,
    ) -> None:
        """Create or refresh a text-content record; called once per page visit.
        Details: docs/dev/core/interfaces.md#record_text_content
        """
        raise NotImplementedError

    def record_text_contents(self, site: str, page_url: str, entries: List[Dict[str, Any]]) -> None:
        """Batched `record_text_content`: each item is a kwargs dict matching
        `record_text_content`'s own signature (minus `site`/`page_url`). Not
        abstract - see `record_components` for why.
        Details: docs/dev/core/interfaces.md#record_text_contents
        """
        for item in entries:
            self.record_text_content(site, page_url, **item)

    @abstractmethod
    def get_text_content_ledger(self, site: str) -> Dict[str, List[Dict[str, Any]]]:
        """{page_url: [{"path", "tag", "text", "visible", "x", "y", "width", "height"}, ...]}."""
        raise NotImplementedError
