"""
Mock agent implementation for testing Pragma.
"""
from __future__ import annotations

from typing import Optional

from ..core.interfaces import Agent
from ..core.registry import AGENT_REGISTRY


@AGENT_REGISTRY.register("mock")
class MockAgent(Agent):
    """A heuristic mock agent that returns static PRD structures."""

    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Return a static mock PRD; `system_instruction` is ignored."""
        links = [line for line in prompt.split("\n") if line.startswith("http")]
        return (
            "# PRD (Mock)\n\n"
            "## Summary\n"
            "A mock PRD generated for testing purposes.\n\n"
            "## Extracted Links\n"
            f"{' '.join(links[:20])}\n\n"
            "## Notes\n"
            "Generated by MockAgent because no real agent key was provided."
        )
