from abc import ABC, abstractmethod
from typing import Dict, Any

class Scraper(ABC):
    @abstractmethod
    def scrape(self, url: str) -> Dict[str, Any]:
        """Return a dict with keys like 'html' and 'links'"""
        raise NotImplementedError

class Agent(ABC):
    @abstractmethod
    def generate(self, prompt: str) -> str:
        """Return text generated by an LLM or agent backend"""
        raise NotImplementedError

class PRDGenerator(ABC):
    @abstractmethod
    def generate_prd(self, scraped: Dict[str, Any]) -> str:
        """Return PRD markdown text"""
        raise NotImplementedError
