"""
Core interfaces for the Pragma project.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional


class Scraper(ABC):
    """Interface for web scrapers."""

    @abstractmethod
    def navigate(self, url: str) -> Dict[str, Any]:
        """Navigate to a URL and return the page state.

        Args:
            url: The target URL to navigate to.

        Returns:
            A dictionary containing the page state.
        """
        raise NotImplementedError

    @abstractmethod
    def click(self, selector: str) -> Dict[str, Any]:
        """Click an element and return the new page state.

        Args:
            selector: CSS selector or text description of the element.

        Returns:
            A dictionary containing the new page state.
        """
        raise NotImplementedError

    @abstractmethod
    def get_state(self) -> Dict[str, Any]:
        """Return the current state of the page.

        Returns:
            A dictionary with keys like 'html', 'url', 'links', and 'interactive_elements'.
        """
        raise NotImplementedError

    @abstractmethod
    def close(self) -> None:
        """Close the browser session and clean up resources."""
        raise NotImplementedError


class Agent(ABC):
    """Interface for AI agent backends."""

    @abstractmethod
    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Return text generated by an LLM or agent backend.

        Args:
            prompt: The user prompt to process.
            system_instruction: Optional system-level instructions or persona.

        Returns:
            The generated response text.
        """
        raise NotImplementedError


class PRDGenerator(ABC):
    """Interface for PRD generation orchestration."""

    @abstractmethod
    def generate_prd(self, url: str) -> str:
        """Orchestrate the agent to explore the URL and generate a PRD.

        Args:
            url: The starting URL for exploration.

        Returns:
            The final PRD in Markdown format.
        """
        raise NotImplementedError
