import os
import sys
from datetime import datetime
from pathlib import Path

# Ensure project root is on path
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from dotenv import load_dotenv
load_dotenv(override=True)

from src.scrapers.playwright_scraper import PlaywrightScraper
from src.generators.prd_generator import SimplePRDGenerator

class MockAgent:
    def generate(self, prompt: str) -> str:
        # Very small heuristic PRD generator using the prompt parts
        return ("# PRD (Mock)\n\n"
                "## Summary\nA mock PRD generated for testing.\n\n"
                "## Extracted Links\n" + '\n'.join([l for l in prompt.split('\n') if l.startswith('http')][:20]) + "\n\n"
                "## Notes\nGenerated by MockAgent because no real agent key was provided.")


def slugify(url: str) -> str:
    return url.replace('https://','').replace('http://','').replace('/','_')


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('url')
    args = parser.parse_args()
    url = args.url

    scraper = PlaywrightScraper(headless=True)
    print('Scraping', url)
    scraped = scraper.scrape(url)
    print('Scraped: html length', len(scraped.get('html','')) , 'links', len(scraped.get('links',[])))

    # Use real agent if API key present, else MockAgent
    if os.getenv('OPENAI_API_KEY'):
        try:
            from src.agents.openai_agent import OpenAIAgent
            agent = OpenAIAgent()
        except Exception as e:
            print('Failed to initialize OpenAIAgent:', e)
            agent = MockAgent()
    else:
        agent = MockAgent()

    prd_gen = SimplePRDGenerator(agent)
    prd = prd_gen.generate_prd(scraped)

    outdir = Path('docs')
    outdir.mkdir(parents=True, exist_ok=True)
    filename = outdir / f"{slugify(url)}_prd_{datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')}.md"
    filename.write_text(prd, encoding='utf-8')
    print('Wrote PRD to', filename)

if __name__ == '__main__':
    main()
